version: 2
updates:
  - package-ecosystem: "npm"
    open-pull-requests-limit: 50
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"

  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 50
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
