name: project-lifecycle

on:
  schedule:
    - cron: 0 8 * * *
  workflow_dispatch:
  issues:
    types:
      - reopened
      - opened
      - labeled

permissions:
  contents: read # for checking out the repository (e.g. actions/checkout)
  issues: write # for editing issues (e.g. adding labels)

jobs:
  lifecycle:
    uses: kumahq/.github/.github/workflows/wfc_lifecycle.yml@main
    with:
      filesToIgnore: CODEOWNERS
