name: 'Tests'

# Runs the project’s linter and test scripts.

on:
  push:
    branches: [master, 'release-[0-9]+.[0-9]+']
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - uses: actions/cache@v3
        id: node-modules-cache
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}

      - if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: |
          yarn run lint:lockfile
          yarn install --frozen-lockfile
          npx cypress install
  lint:
    needs: [install-dependencies]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - uses: actions/cache@v3
        id: node-modules-cache
        with:
          path: |
            **/node_modules
            /home/runner/.cache
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
      - env:
          LINTER_MODE: strict
        run: |
          yarn run lint
          yarn run lint:ts
  tests:
    needs: [install-dependencies]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - uses: actions/cache@v3
        id: node-modules-cache
        with:
          path: |
            **/node_modules
            /home/runner/.cache
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn run test
      - run: |
          yarn run preview &
          yarn run test:browser
