# create-gui-pr.yaml is dependant on this name being "Tests"
name: 'Tests'
#
on:
  push:
    branches: [master, 'release-[0-9]+.[0-9]+']
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - uses: actions/cache@v3
        id: node-modules-cache
        with:
          path: |
            **/node_modules
            /home/runner/.cache
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}

      - if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: |
          yarn install --frozen-lockfile
          yarn run lint:lockfile
          yarn deps

  lint-tests:
    needs: [install-dependencies]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - uses: actions/cache/restore@v3
        id: node-modules-cache
        with:
          path: |
            **/node_modules
            /home/runner/.cache
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
      - env:
          LINTER_MODE: strict
        run: |
          yarn run lint
          yarn run lint:ts
          yarn run lint:styles

  cli-tests:
    needs: [install-dependencies]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - uses: actions/cache/restore@v3
        id: node-modules-cache
        with:
          path: |
            **/node_modules
            /home/runner/.cache
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
      - run: |
          yarn run test

  browser-tests:
    needs: [install-dependencies]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - uses: actions/cache/restore@v3
        id: node-modules-cache
        with:
          path: |
            **/node_modules
            /home/runner/.cache
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
      - run: |
          yarn build:staging
      - run: |
          yarn preview:built &
          CYPRESS_video=true yarn run test:browser
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-artifacts
          retention-days: ${{ github.event_name == 'pull_request' && 3 || 30 }}
          path: |
            cypress/screenshots
            cypress/videos

  post-checks:
    # There is a branch protection rule on the repo that requires "branch-protection" to
    # be successful
    name: branch-protection
    #
    needs:
      - lint-tests
      - cli-tests
      - browser-tests
    runs-on: ubuntu-latest
    if: |
      always()
    steps:
      - name: Check for failures
        if: |
          contains(needs.*.result, 'failure') ||
          contains(needs.*.result, 'cancelled')
        run: echo '${{toJSON(needs)}}' && exit 1

      - run: echo "Successful"
