name: 'Tests'

# Runs the project’s linter and test scripts.

on:
  push:
    branches: [master, 'release-[0-9]+.[0-9]+']
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  install-dependencies:
    # Skip this job if the head commit’s message contains the string “[skip ci]”.
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    name: 'Install dependencies'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        # https://github.com/actions/checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        # https://github.com/actions/setup-node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Cache node_modules
        # https://github.com/actions/cache
        uses: actions/cache@v3
        id: node-modules-cache
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Lint lock file
        run: yarn run lint:lockfile

  tests:
    needs: [install-dependencies]
    # Skip this job if the head commit’s message contains the string “[skip ci]”.
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    name: 'Tests'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        # https://github.com/actions/checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        # https://github.com/actions/setup-node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Cache node_modules
        # https://github.com/actions/cache
        uses: actions/cache@v3
        id: node-modules-cache
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Lint
        run: yarn run lint
        env:
          LINTER_MODE: strict

      - name: Lint TS
        run: yarn run lint:ts

      - name: Test
        run: yarn run test

      - name: Build
        run: yarn run build
