name: 'Tests'
on:
  push:
    branches: [master, 'release-[0-9]+.[0-9]+']
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - uses: actions/cache@v3
        id: node-modules-cache
        with:
          path: |
            **/node_modules
            /home/runner/.cache
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}

      - if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: |
          yarn install --frozen-lockfile
          yarn run lint:lockfile
          yarn deps

  pre-checks:
    needs: [install-dependencies]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - uses: actions/cache@v3
        id: node-modules-cache
        with:
          path: |
            **/node_modules
            /home/runner/.cache
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
      - env:
          LINTER_MODE: strict
        run: |
          yarn run lint
          yarn run lint:ts

  cli-tests:
    needs: [install-dependencies]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - uses: actions/cache@v3
        id: node-modules-cache
        with:
          path: |
            **/node_modules
            /home/runner/.cache
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
      - run: |
          yarn run test

  browser-tests:
    needs: [install-dependencies]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - uses: actions/cache@v3
        id: node-modules-cache
        with:
          path: |
            **/node_modules
            /home/runner/.cache
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
      - run: |
          yarn build:staging
      - run: |
          yarn preview:built &
          yarn run test:browser

  post-checks:
    # There is a branch protection rule on the repo that requires "Tests" to
    # be successful
    name: Tests
    #
    needs:
      - pre-checks
      - cli-tests
      - browser-tests
    runs-on: ubuntu-latest
    if: |
      (always() && !cancelled()) &&
      !contains(needs.*.result, 'failure') &&
      !contains(needs.*.result, 'skipped') &&
      !contains(needs.*.result, 'cancelled')
    steps:
      - run: echo "Tests passed"
