name: 'On Dependabot PR'

# Ensures that only one workflow is run per branch at a time.
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}

on: pull_request

permissions:
  pull-requests: write

jobs:
  dependabot-labels:
    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == 'kumahq/kuma-gui'
    runs-on: ubuntu-latest
    steps:
      - uses: dependabot/fetch-metadata@v2
        id: metadata
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Add a label for all production dependencies
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
        if: steps.metadata.outputs.dependency-type == 'direct:production'
        run: gh pr edit "$PR_URL" --add-label "production"
